[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/vimproc.vim'
# theme
[[plugins]]
repo = 'NLKNguyen/papercolor-theme'
[[plugins]]
repo = 'jonathanfilip/vim-lucius'
[[plugins]]
repo = 'cocopon/iceberg.vim'

## airline
#[[plugins]]
#repo = 'vim-airline/vim-airline'
#[[plugins]]
#repo = 'vim-airline/vim-airline-themes'

# lightline
[[plugins]]
repo = 'itchyny/lightline.vim'

# general
[[plugins]]
repo = 'kassio/neoterm'
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'severin-lemaignan/vim-minimap'

# completion
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

# syntax
[[plugins]]
repo = 'w0rp/ale'
[[plugins]]
repo = 'godlygeek/tabular'
