[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/vimproc.vim'
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
[[plugins]]
repo = 'roxma/nvim-yarp'
# themes
[[plugins]]
repo = 'jonathanfilip/vim-lucius'
[[plugins]]
repo = 'jacoborus/tender.vim'

# lightline
[[plugins]]
repo = 'itchyny/lightline.vim'

# general
[[plugins]]
repo = 'junegunn/fzf.vim'
[[plugins]]
repo = '/usr/local/opt/fzf'
[[plugins]]
repo = 'Yggdroot/indentLine'
[[plugins]]
repo = 'Shougo/neomru.vim'
[[plugins]]
repo = 'wsdjeg/FlyGrep.vim'
[[plugins]]
repo = 'hecal3/vim-leader-guide'

# git
[[plugins]]
repo = 'airblade/vim-gitgutter'

# Vim plugin: Turn :cd into :tabpagecd, to use one tab page per project
[[plugins]]
repo = 'kana/vim-tabpagecd'
# multiple-cursors
[[plugins]]
repo = 'terryma/vim-multiple-cursors'
[[plugins]]
repo = 'mileszs/ack.vim'

# completion
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'cohama/lexima.vim'

# syntax
[[plugins]]
repo = 'w0rp/ale'
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
