# fish
[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']

# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# Markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md', 'markdown']

# Ruby
# Need fastri, neovim, rcodetools gems
[[plugins]]
repo = 'uplus/deoplete-solargraph'
on_ft = ['rb', 'ruby']

# Elixir
[[plugins]]
repo = 'elixir-editors/vim-elixir'
on_ft = ['ex', 'exs', 'eex']
[[plugins]]
repo = 'slashmili/alchemist.vim'
on_ft = ['ex', 'exs', 'eex']

# Go
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = ['go']
hook_post_update = '''
	let g:dein#plugin.build = 'make'
'''
hook_add = '''
	let g:deoplete#sources#go#gocode_binary = $GOPATH.'/bin/gocode'
	let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
'''

# Rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rs', 'rust']

# javascript
## ES6
# Vue.js
[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']
